### PR TITLE
Update model-masking.md STU-319

### PR DESCRIPTION
**Pull request by chris-miaskowski**
I'm proposing this change as a result of my work on the Masking API.

The advantages of the structure I propose is the following:

- type safety
- better GraphQL support
- type predictability (as a developer I know immediately what `selected` is)

In a DB we can still store it as JSON object, but we get GraphQL support. 

Consider these examples.

**Example 1: current schema and implementation consequences**

Sad, poor types :(

`input.ts`

```ts
// @ts-ignore
import { GraphQLJSONObject } from 'graphql-type-json';
import { Field, InputType } from 'type-graphql';

@InputType()
export class MaskInputLoose {
  @Field(() => GraphQLJSONObject)
  public selected: JSON; // so sad ;(
}
```

image

**Example 2: proposed schema and implementation consequences**

Nice, clean types

`inputs.ts`

```ts
import { Field, InputType } from 'type-graphql';
import { MaskData } from './types';

@InputType()
export class MaskInputStrict {
  @Field(type => MaskData)
  public selected: MaskData;
}
```

`types.ts`

```ts
import { Field, InputType, ObjectType } from 'type-graphql';

@ObjectType()
@InputType('MaskSelectionInput')
export class MaskSelection {
  @Field()
  public path: string;
  @Field({ nullable: true })
  public required?: boolean;
}

@ObjectType()
@InputType('MaskDataInput')
export class MaskData {
  @Field(type => [MaskSelection])
  public selected: MaskSelection[];
}
```

image

image

### CODE REVIEW

**Comment by chris-miaskowski** [comment]
I will go forward with the proposed solution before I get a chance to hear feedback as I strongly believe it's better (and don't want to get blocked). I'm happy to be proven otherwise, though!

**Comment by brianmrock** [comment]
Can you provide some concrete examples here?

**Comment by chris-miaskowski** [comment]
Sure @brianmrock.

The main difference is the types though (see the print screens). Note how in the current design `selected` is just a vague `JSONObject`.

Otoh my proposal makes it easy to understand than `selected` is an array with `paths` and optional `required`

Here is a concrete example of how that may look like. Also I will created a draft PR (https://github.com/stoplightio/api-gen3/pull/107) which has two implementations (`masks` vs `loosemasks` - my proposal is in `masks`)

```yaml 
id: 1
node_id: 1
node_version_id: 1
data:
  selected:
    - path: /a/b/c
      required: true
    - path: /x/y 
```

**Comment by pytlesk4** [comment]
The implementation would be considerably different. Between solution one and yours, solution one is a lot easier.

Also, what's the reasoning for wrapping selected in data? Why not just have selected be its own column?

```yml
selected:
  - path: /a/b/c
    required: true
  - path: /x/y
```

What is data_hash for?

**Comment by marbemac** [comment]
@pytlesk4 some of your questions are answered in the design doc - https://github.com/stoplightio/design-docs/blob/master/docs/model-masking.md#database.

**Comment by chris-miaskowski** [comment]
Thanks @marbemac!
@pytlesk4 good questions. The link that @marbemac provided should hopefully answer all of them.

> The implementation would be considerably different. Between solution one and yours, solution one is a lot easier.

I have tried both implementations and the proposed design isn't really more or less complex (just different).

**Pull request merged**
